DECLARE
  TODAY DATE := SYSDATE;
  TOMORROW TODAY%TYPE; 

BEGIN
  DBMS_OUTPUT.PUT_LINE('Hello World');

  TOMORROW := TODAY + 1;

  DBMS_OUTPUT.PUT_LINE('Today: ' || TO_CHAR(TODAY, 'Month DD, YYYY'));
  DBMS_OUTPUT.PUT_LINE('Tomorrow: ' || TO_CHAR(TOMORROW, 'Month DD, YYYY'));

END;